[project]
authors = ["r1cheu <chenrulei@cemps.ac.cn>"]
channels = ["conda-forge"]
name = "gelex"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]
configure = { cmd = [
  "cmake",
  "-G",
  "Ninja",
  "-S",
  ".",
  "-B",
  ".build",
  "-D",
  "BUILD_TEST=ON",
] }
build = { cmd = "ninja -C .build -j24", depends-on = ["configure"] }
test = { cmd = "./.build/tests/test", depends-on = ["build"] }


[dependencies]
cmake = ">=3.18,<4"
cxx-compiler = ">=1.8.0,<2"
make = ">=4.4.1,<5"
ninja = ">=1.12.1,<2"
openblas = { version = ">=0.3.28", build = "*openmp*" }
spdlog = ">=1.15.0,<2"
catch2 = ">=3.8.0,<4"
mkl = ">=2024.0.0,<2026"
